# Project: Proyecto 1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = Proyecto_1_private.res
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"C:/Users/UD1/Desktop/Dev-CppPortable/App/devcpp/lib" -lconio -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32 
INCS =  -I"C:/Users/UD1/Desktop/Dev-CppPortable/App/devcpp/include" 
CXXINCS =  -I"C:/Users/UD1/Desktop/Dev-CppPortable/App/devcpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/UD1/Desktop/Dev-CppPortable/App/devcpp/include/c++/3.4.2/backward"  -I"C:/Users/UD1/Desktop/Dev-CppPortable/App/devcpp/include/c++/3.4.2/mingw32"  -I"C:/Users/UD1/Desktop/Dev-CppPortable/App/devcpp/include/c++/3.4.2"  -I"C:/Users/UD1/Desktop/Dev-CppPortable/App/devcpp/include" 
BIN  = "Proyecto 1.exe"
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before "Proyecto 1.exe" all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Proyecto 1.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Proyecto_1_private.res: Proyecto_1_private.rc 
	$(WINDRES) -i Proyecto_1_private.rc --input-format=rc -o Proyecto_1_private.res -O coff 
